env:
  name: "Humanoid-v5"
  num_envs: 1 # parallel envs nubmer

#ppo hyperparams
algorithm:
  name: "ppo"
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.0
  value_coef: 0.5
  num_epochs: 10
  minibatch_size: 64

# training conf
training:
  totale_timesteps: 2_000_000
  rollout_steps: 2048
  learning_rate: 0.0003

#nn architecture
model:
  policy_hidden_dims: [64, 64]
  value_hidden_dims: [64, 64]